version: '3.8'

services:
  php:
    build: .
    container_name: lab9_php
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db_test
      - DB_NAME=test_db
      - DB_USER=test_user
      - DB_PASSWORD=test_pass
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db_test
      - rabbitmq
    networks:
      - ci_network

  db_test:
    image: mysql:8.0
    container_name: lab9_db_test
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    networks:
      - ci_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab9_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ci_network

networks:
  ci_network:
    driver: bridge