version: '3.8'
services:
  php:
    build: .
    container_name: lab9_php
    volumes:
      - .:/var/www/html
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab9_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"